# Simple workflow for deploying static content to GitHub Pages
name: Deploy content to Pages
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency: ci-${{ github.ref }}
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true # Fetches LFS data
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Bundle
        run: |
          pnpm install
          pnpm build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/website/build # The folder the action should deploy.
